version: '5.0'

actions:

  extract_data:
    run: ehrql:v1 generate-dataset analysis/01_dataset_definition.py
      --dummy-tables dummy_tables
      --output output/highly_sensitive/dataset_death_ons_tpp.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/highly_sensitive/dataset_death_ons_tpp.csv.gz

  apply_inclusion_exclusion:
    needs: [extract_data]
    run: r:v2 analysis/02_inclusion_exclusion_criteria.R
    outputs:
      highly_sensitive:
        cohort: output/02_cohort.csv
      moderately_sensitive:
        cohort_flow: output/02_cohort_flow.csv

  extract_underlying_cause_summary:
    needs: [apply_inclusion_exclusion]
    run: r:v2 analysis/03_extract_underlying_cause_summary.R
    outputs:
      moderately_sensitive:
        underlying_cause_summary: output/03_underlying_cause_summary.csv

  add_classifications:
    needs: [extract_underlying_cause_summary]
    run: r:v2 analysis/04_add_classifications.R
    outputs:
      moderately_sensitive:
        broad_cause_classification: output/04_broad_cause_classification.csv
        broad_cause_codes_for_review: output/04_broad_cause_codes_for_review.csv

  analysis:
    needs: [apply_inclusion_exclusion, add_classifications]
    run: r:v2 analysis/05_analysis.R
    outputs:
      moderately_sensitive:
        diagnostic_table: output/05_tpp_diagnostic_summary.csv