###################################################
# Author: Irene Kyomuhangi
#   Bennett Institute for Applied Data Science
#   University of Oxford, 2026
####################################################
# Purpose:
# Extract underlying cause of death summary from ONS data 
#
# Step 1: Apply inclusion/exclusion criteria to the dataset
# Inclusion criteria:
#   - Registered death in the ONS dataset
#   - ONS date of death on or after the study start date
#   - ONS date of death on or before the study end date (6 months before latest data extract)
#   - Registered with a TPP practice on the date of death
# Exclusion criteria:
#   - Age > 110 years >> *already applied in the dataset definition
#   - Missing or impossible age >> *already applied in the dataset definition
#   - Missing sex >> *already applied in the dataset definition
#   - Death before date of birth
#
# Step 2: Extract a summary table listing the underlying cause of death, and the number of cases 
# of that death (applying disclosure control to those counts)
###################################################


library(dplyr)
library(readr)

# =============================================================================
# Set parameters
# =============================================================================

# Set Prefix for all output files generated by this script.
# This should match the script number (e.g. "01", "02", "03")
script_prefix <- "02"

# Set the study start/end dates
study_start_date <- as.Date("2022-01-01")
study_end_date <- as.Date("2026-02-01") # Update study_end_date to match the most recent available ONS extract


# -----------------------------------------------------------------------------
# Read data
# -----------------------------------------------------------------------------
# Read extracted OpenSAFELY dataset (dummy or real)
death_data <- read_csv(
  "output/highly_sensitive/dataset_death_ons_tpp.csv.gz"
)

# -----------------------------------------------------------------------------
# Apply study inclusion and exclusion criteria
# -----------------------------------------------------------------------------

# ---------------
# Create individual flags for the inclusion/exclusion criteria
death_data <- death_data %>%
  mutate(
    ons_death_date = as.Date(ons_death_date),
    date_of_birth = as.Date(date_of_birth),
    last_registration_start_date = as.Date(last_registration_start_date),
    last_registration_end_date = as.Date(last_registration_end_date),

    # Flag when ONS death occurred within the study period
    in_study_period =
      ons_death_date >= study_start_date &
      ons_death_date <= study_end_date,

    # Flag when ONS date of death is on or after the date of birth
    valid_date_sequence =
      !is.na(date_of_birth) &
      ons_death_date >= date_of_birth,

    # Flag when individual was registered with a TPP practice on the ONS date of death
    registered_at_death =
      !is.na(last_registration_start_date) &
      last_registration_start_date <= ons_death_date &
      (
        is.na(last_registration_end_date) |
          last_registration_end_date >= ons_death_date
      )
  )

# ---------------
# Step 1: Restrict the cohort to deaths occurring within the study period
within_study_period <- death_data %>%
  filter(in_study_period)

outside_study_period <- death_data %>%
  filter(!in_study_period)

# ---------------
# Step 2: Exclude records with impossible date sequences (i.e Death before date of birth)
valid_date_sequence_data <- within_study_period %>%
  filter(valid_date_sequence)

impossible_date_sequence <- within_study_period %>%
  filter(!valid_date_sequence)

# ---------------
# Step 3: Include only those registered at death
analysis_cohort <- valid_date_sequence_data %>%
  filter(registered_at_death)

not_registered_at_death <- valid_date_sequence_data %>%
  filter(!registered_at_death)


# -----------------------------------------------------------------------------
# Cohort flow summary
# -----------------------------------------------------------------------------

cohort_flow <- tibble(
  step = c(
    "Total records",
    "Excluded: outside study period",
    "Excluded: death before date of birth or missing date of birth",
    "Excluded: not registered with TPP at death",
    "Final analytical cohort"
  ),
  n = c(
    nrow(death_data),
    nrow(outside_study_period),
    nrow(impossible_date_sequence),
    nrow(not_registered_at_death),
    nrow(analysis_cohort)
  )
)

write_csv(
  cohort_flow,
  paste0("output/", script_prefix, "_cohort_flow.csv")
)


# -----------------------------------------------------------------------------
# Summarise underlying cause of death
# -----------------------------------------------------------------------------

# Summarise underlying cause of death codes & apply disclosure control to the counts
underlying_cause_summary <- analysis_cohort %>%
  count(underlying_cause_of_death, name = "n_records") %>%
  mutate(
    n_records = if_else(
      n_records <= 7,
      "[REDACTED]",
      as.character(round(n_records / 5) * 5)
    )
  ) %>%
  arrange(underlying_cause_of_death)

write_csv(
  underlying_cause_summary,
  "output/02_underlying_cause_summary.csv"
)


# -----------------------------------------------------------------------------
# Save cohort
# -----------------------------------------------------------------------------

write_csv(
  analysis_cohort,
  paste0("output/", script_prefix, "_cohort.csv")
)
