###################################################
# Author: Irene Kyomuhangi
#   Bennett Institute for Applied Data Science
#   University of Oxford, 2026
####################################################
# Purpose:
# Apply inclusion/exclusion criteria to the dataset
# Inclusion criteria:
#   - Registered death in the ONS dataset
#   - ONS date of death on or after 1 January 2022
#   - Registered with a TPP practice on the date of death
#
# Exclusion criteria:
#   - Age >110 years
#   - Missing or impossible age
#   - Missing sex
#   - Death before date of birth
###################################################


library(dplyr)
library(readr)

# Set Prefix for all output files generated by this script.
# This should match the script number (e.g. "01", "02", "03")
script_prefix <- "02" 


# =============================================================================
# Read data
# =============================================================================
# Read extracted OpenSAFELY dataset (dummy or real)
death_data <- read_csv(
  "output/dummy_dataset.csv"
)

# =============================================================================
# Apply study inclusion and exclusion criteria
# =============================================================================

analysis_cohort <- death_data %>%
  mutate(
    ons_death_date = as.Date(ons_death_date),
    date_of_birth = as.Date(date_of_birth),
    last_registration_start_date = as.Date(last_registration_start_date),
    last_registration_end_date = as.Date(last_registration_end_date)
  ) %>%
  filter(

    # Study period
    ons_death_date >= as.Date("2022-01-01"),

    # Valid age
    !is.na(age),
    age >= 0,
    age <= 110,

    # Valid date sequence
    ons_death_date >= date_of_birth,

    # Registered with a TPP practice on the ONS death date
    !is.na(last_registration_start_date),
    last_registration_start_date <= ons_death_date,
    is.na(last_registration_end_date) |
      last_registration_end_date >= ons_death_date

  )

# =============================================================================
# Quality assurance
#
# Summarise the number of records before and after applying the study
# inclusion and exclusion criteria.
# =============================================================================

cohort_summary <- tibble(
  total_records = nrow(death_data),
  included_records = nrow(analysis_cohort),
  excluded_records = nrow(death_data) - nrow(analysis_cohort)
)

write_csv(
  cohort_summary,
  paste0(
    "output/",
    script_prefix,
    "_cohort_summary.csv"
  )
)

# =============================================================================
# Save analytical cohort
# =============================================================================

write_csv(
  analysis_cohort,
  paste0(
    "output/",
    script_prefix,
    "_analysis_cohort.csv"
  )
)