###################################################
# Author: Irene Kyomuhangi
#   Bennett Institute for Applied Data Science
#   University of Oxford, 2026
####################################################
# Purpose:
#   1. Read extracted OpenSAFELY dataset (real or dummy data)
#   2. Read ICD-10 classification Excel file
#   3. Merge classifications onto dataset
###################################################


library(dplyr)
library(readr)

# Set Prefix for all output files generated by this script.
# This should match the script number (e.g. "01", "02", "03")
script_prefix <- "03"

# =============================================================================
# Read data
# =============================================================================

# Read extracted OpenSAFELY dataset (dummy or real)
analysis_cohort <- read_csv(
  "output/02_cohort.csv"
)

# Read ICD-10 classification table
death_classifications <- read_csv(
  "analysis/classifications/icd10_classifications.csv"
)

# =============================================================================
# Merge ICD-10 classifications
# =============================================================================

death_data_with_classifications <- analysis_cohort %>%
  left_join(
    death_classifications,
    by = c(
      "underlying_cause_of_death" = "code"
    )
  )

# =============================================================================
# Quality assurance
# =============================================================================

# Classification summary: Summarise the number of matched and unmatched ICD-10
# classifications after merging
classification_summary <- death_data_with_classifications %>%
  summarise(
    total_records = n(),
    unmatched_records = sum(is.na(cause_group)),
    matched_records = total_records - unmatched_records
  )

write_csv(
  classification_summary,
  paste0("output/", script_prefix, "_classification_summary.csv")
)

# Summarise ICD-10 codes that were not assigned to a classification after
# merging. Counts fewer than 5 are suppressed for disclosure
# control.

unmatched_codes <- death_data_with_classifications %>%
  filter(is.na(cause_group)) %>%
  count(underlying_cause_of_death, name = "n_records") %>%
  mutate(
    n_records = if_else(
      n_records < 5,
      "<5",
      as.character(n_records)
    )
  ) %>%
  arrange(underlying_cause_of_death)

write_csv(
  unmatched_codes,
  paste0("output/", script_prefix, "_unmatched_icd10_codes.csv")
)

# =============================================================================
# Save merged dataset
# =============================================================================

write_csv(
  death_data_with_classifications,
  paste0("output/", script_prefix, "_cohort_with_classifications.csv")
)
