###################################################
# Author: Irene Kyomuhangi
#   Bennett Institute for Applied Data Science
#   University of Oxford, 2026
####################################################
# Purpose:
#   Extract and summarise underlying cause of death
#   from the final analytical cohort, applying
#   statistical disclosure control to the counts.
###################################################


library(dplyr)
library(readr)

# =============================================================================
# Set parameters
# =============================================================================

# Set Prefix for all output files generated by this script.
# This should match the script number (e.g. "01", "02", "03")
script_prefix <- "03"


# -----------------------------------------------------------------------------
# Read data
# -----------------------------------------------------------------------------

# Read the final analytical cohort created by the inclusion/exclusion script
analysis_cohort <- read_csv(
  "output/02_cohort.csv"
)


# -----------------------------------------------------------------------------
# Summarise underlying cause of death
# -----------------------------------------------------------------------------

# Summarise underlying cause of death codes and apply disclosure control
# to the counts
underlying_cause_summary <- analysis_cohort %>%
  count(underlying_cause_of_death, name = "n_records") %>%
  mutate(
    n_records = if_else(
      n_records <= 7,
      "[REDACTED]",
      as.character(round(n_records / 5) * 5)
    )
  ) %>%
  arrange(underlying_cause_of_death)

write_csv(
  underlying_cause_summary,
  paste0("output/", script_prefix, "_underlying_cause_summary.csv")
)