###################################################
# Author: Irene Kyomuhangi
#   Bennett Institute for Applied Data Science
#   University of Oxford, 2026
####################################################
# Purpose:
#   Assign classifications to
#   the underlying cause-of-death codes observed in
#   the analytical cohort.
#   - broad cause of death
#   - death circumstance (to be added)
#   - likelihood of coroner referral (to be added)
#   - registration complexity (to be added)
####################################################


library(dplyr)
library(readr)
library(stringr)

# -----------------------------------------------------------------------------
# Import utilities
# -----------------------------------------------------------------------------

source("analysis/00_utilities.R")


# -----------------------------------------------------------------------------
# Set parameters
# -----------------------------------------------------------------------------

# Set Prefix for all output files generated by this script.
# This should match the script number (e.g. "01", "02", "03", "04")
script_prefix <- "04"


# -----------------------------------------------------------------------------
# Read data
# -----------------------------------------------------------------------------

# Read the underlying cause-of-death summary created by script 03
underlying_cause_summary <- read_csv(
  "output/03_underlying_cause_summary.csv"
)


# =============================================================================
# Broad cause-of-death group
# =============================================================================

# Assign observed ICD-10 codes to broad cause-of-death groups.
#
# The classification is based primarily on the ICD-10 chapter structure,
# with selected clinically relevant exceptions and combinations.
#
# Broad cause-of-death groups:
#   - neoplasms
#   - cardiovascular disease
#   - respiratory disease
#   - neurological and dementia disorders
#   - infectious diseases
#   - external causes and injuries
#   - perinatal/congenital/maternal causes
#   - ill-defined/unknown causes
#   - other medical conditions and findings
#   - missing
#
# The groups are intended to provide clinically meaningful categories for
# analyses of discordance in recorded date of death. They do not aim to
# reproduce ICD-10 chapters exactly.
#
# Neoplasms
# ICD-10 C00-D48: malignant, in-situ, benign and uncertain/unknown behaviour
# neoplasms
#
# Cardiovascular disease
# ICD-10 I00-I99: diseases of the circulatory system
#
# Respiratory disease
# ICD-10 J00-J99: diseases of the respiratory system
# U07.0: vaping-related disorder
#
# Neurological and dementia disorders
# ICD-10 G00-G99: diseases of the nervous system
# F00-F03: dementia
#
# Infectious diseases
# ICD-10 A00-B99: certain infectious and parasitic diseases
# U04.9: severe acute respiratory syndrome [SARS]
# U07.1/U07.2: COVID-19
# U10.9: multisystem inflammatory syndrome associated with COVID-19
#
# External causes and injuries
# ICD-10 S00-T98: injury, poisoning and certain other consequences of
# external causes
# ICD-10 V00-Y89: external causes of morbidity and mortality
# U12.9: adverse effect of COVID-19 vaccine
# U50.9: deaths awaiting determination of intent
#
# Perinatal/congenital/maternal causes
# ICD-10 O00-O99: pregnancy, childbirth and the puerperium
# ICD-10 P00-P96: conditions originating in the perinatal period
# ICD-10 Q00-Q99: congenital malformations and chromosomal abnormalities
#
# Ill-defined/unknown causes
# ICD-10 R95-R99: ill-defined and unknown causes of mortality
#
# Other medical conditions and findings
# Remaining medical conditions and findings not included in the groups above
# This includes D50-D89, E00-E90, F04-F99, H00-H95, K00-K93, L00-L99,
# M00-M99, N00-N99 and R00-R94
#
# Missing
# Records with no underlying cause-of-death ICD-10 code


broad_cause_classification <- underlying_cause_summary %>%
  mutate(
    broad_cause_group = case_when(

      # Infectious diseases
      str_detect(underlying_cause_of_death, "^[AB]") |
        str_detect(
          underlying_cause_of_death,
          "^U049$|^U071$|^U072$|^U109$"
        ) ~
        "infectious diseases",

      # Neoplasms
      str_detect(underlying_cause_of_death, "^C") |
        str_detect(
          underlying_cause_of_death,
          "^D(0[0-9]|[1-3][0-9]|4[0-8])"
        ) ~
        "neoplasms",

      # Cardiovascular disease
      str_detect(underlying_cause_of_death, "^I") ~
        "cardiovascular disease",

      # Respiratory disease
      str_detect(underlying_cause_of_death, "^J") |
        underlying_cause_of_death == "U070" ~
        "respiratory disease",

      # Neurological and dementia disorders
      str_detect(underlying_cause_of_death, "^G") |
        str_detect(underlying_cause_of_death, "^F0[0-3]") ~
        "neurological and dementia disorders",

      # External causes and injuries
      str_detect(underlying_cause_of_death, "^[STVWX]") |
        str_detect(
          underlying_cause_of_death,
          "^Y(0[0-9]|[1-8][0-9])"
        ) |
        str_detect(
          underlying_cause_of_death,
          "^U129$|^U509$"
        ) ~
        "external causes and injuries",

      # Perinatal/congenital/maternal causes
      str_detect(underlying_cause_of_death, "^[OPQ]") ~
        "perinatal/congenital/maternal causes",

      # Ill-defined/unknown causes
      str_detect(underlying_cause_of_death, "^R9[5-9]") ~
        "ill-defined/unknown causes",

      # Other medical conditions and findings
      str_detect(underlying_cause_of_death, "^[DEFGHKLMNR]") ~
        "other medical conditions and findings",

      # Missing underlying cause
      is.na(underlying_cause_of_death) ~
        "missing",

      # Any unexpected observed codes
      TRUE ~
        "REVIEW"
    )
  )
  
# Check the number of observed codes assigned to each broad cause-of-death group
table(broad_cause_classification$broad_cause_group)

# check how many records are missing underlying_cause_of_death
broad_cause_classification %>%
  filter(broad_cause_group == "missing")

# ----------------
# Codes requiring further review
# Identify any observed ICD-10 codes that have not been assigned
# to a broad cause-of-death group, and need further review
codes_for_review <- broad_cause_classification %>%
  filter(broad_cause_group == "REVIEW") %>%
  arrange(underlying_cause_of_death)


# -----------------------------------------------------------------------------
# Save outputs
# -----------------------------------------------------------------------------

# Save the broad cause-of-death classification for all observed codes
write_csv(
  broad_cause_classification,
  paste0(
    "output/",
    script_prefix,
    "_broad_cause_classification.csv"
  )
)

# Save any observed codes requiring further review
write_csv(
  codes_for_review,
  paste0(
    "output/",
    script_prefix,
    "_broad_cause_codes_for_review.csv"
  )
)


