###################################################
# Author: Irene Kyomuhangi
#   Bennett Institute for Applied Data Science
#   University of Oxford, 2026
####################################################
# Purpose:
#   Conduct descriptive analyses of discordance in
#   recorded date of death for two groups:
#   - individuals with ONS-only date of death
#   - individuals with mismatched recorded date of death
#     for either structural date of death or death code
#   Analyses will examine variation by:
#   - the 4 classifications of underlying cause of death :
#      * broad cause of death
#      * death circumstance (to be added)
#      * likelihood of coroner referral (to be added)
#      * registration complexity (to be added)
#   - place of death (to be added)
#   - practice region (to be added)
#   - practice (to be added)
####################################################


library(dplyr)
library(readr)
library(stringr)


# -----------------------------------------------------------------------------
# Import utilities
# -----------------------------------------------------------------------------

source("analysis/00_utilities.R")


# -----------------------------------------------------------------------------
# Set parameters
# -----------------------------------------------------------------------------

# Set Prefix for all output files generated by this script.
# This should match the script number (e.g. "01", "02", "03", "04", "05")
script_prefix <- "05"


# -----------------------------------------------------------------------------
# Read data
# -----------------------------------------------------------------------------

# Read the final analytical cohort created by script 02
analysis_cohort <- read_csv(
  "output/02_cohort.csv"
)

# Read the broad cause-of-death classifications created by script 04
broad_cause_classification <- read_csv(
  "output/04_broad_cause_classification.csv"
)


# -----------------------------------------------------------------------------
# Merge cause-of-death classifications to final analytical cohort
# -----------------------------------------------------------------------------

analysis_cohort <- analysis_cohort %>%
  left_join(
    broad_cause_classification %>%
      select(
        underlying_cause_of_death,
        broad_cause_group
      ),
    by = "underlying_cause_of_death"
  )


# -----------------------------------------------------------------------------
# Define outcomes
# -----------------------------------------------------------------------------

# Define TPP death recording and the two measures of discordance with ONS:
#
# Outcome 1: ONS-only death
# ONS death recorded, with neither a structured TPP date of death nor a
# TPP coded death record.
#
# Outcome 2: Mismatched recorded date of death
# Among individuals with at least one TPP death record, at least one available
# TPP death date (structured or coded) differs from the ONS date of death.

analysis_cohort <- analysis_cohort %>%
  mutate(

    # TPP death recording
    has_tpp_death_date =
      !is.na(tpp_death_date),

    has_tpp_death_code =
      !is.na(tpp_coded_death_date),

    has_tpp_death_record =
      has_tpp_death_date |
      has_tpp_death_code,

    # ONS death with no death recorded in either TPP source
    ons_only_death =
      !has_tpp_death_record,

    # Mismatch between ONS and structured TPP date of death
    mismatched_tpp_death_date =
      has_tpp_death_date &
      ons_death_date != tpp_death_date,

    # Mismatch between ONS and TPP coded death date
    mismatched_tpp_coded_death_date =
      has_tpp_death_code &
      ons_death_date != tpp_coded_death_date,

    # Mismatch in either available TPP death recording
    mismatched_death_record =
      mismatched_tpp_death_date |
      mismatched_tpp_coded_death_date
  )


# -----------------------------------------------------------------------------
# Diagnostic table
# -----------------------------------------------------------------------------

# Create a diagnostic summary of death recording in TPP.
# These measures are diagnostic checks and are not additional study outcomes.
#
# TPP deaths may be recorded either as a structured date of death or as a
# coded death event. The study outcomes use information from both sources.
# This table is produced as a quality assurance check to show:
#   - how often each type of TPP death record is present;
#   - how often both types of TPP death record are present;
#   - how often the two TPP death dates disagree with each other; and
#   - how often the date from each TPP source differs from the ONS date of death.

diagnostic_table <- tibble(
  measure = c(
    "Structured TPP death date present",
    "TPP coded death present",
    "Both structured TPP death date and TPP coded death present",
    "Structured TPP death date and TPP coded death date mismatch",
    "Structured TPP death and ONS date of death mismatch",
    "TPP coded death date and ONS date of death mismatch"
  ),
  n = c(
    sum(analysis_cohort$has_tpp_death_date),
    sum(analysis_cohort$has_tpp_death_code),
    sum(
      analysis_cohort$has_tpp_death_date &
        analysis_cohort$has_tpp_death_code
    ),
    sum(
      analysis_cohort$has_tpp_death_date &
        analysis_cohort$has_tpp_death_code &
        analysis_cohort$tpp_death_date !=
          analysis_cohort$tpp_coded_death_date
    ),
    sum(analysis_cohort$mismatched_tpp_death_date),
    sum(analysis_cohort$mismatched_tpp_coded_death_date)
  )
)

diagnostic_table <- diagnostic_table %>%
  mutate(
    # Apply statistical disclosure control
    n = apply_sdc(n),

    # Format redacted counts for output
    n = if_else(
      is.na(n),
      "[REDACTED]",
      as.character(n)
    )
  )

write_csv(
  diagnostic_table,
  paste0(
    "output/",
    script_prefix,
    "_tpp_death_recording_diagnostic.csv"
  )
)


# =============================================================================
# Broad cause-of-death analysis
# =============================================================================

# Summarise death recording and discordance by broad cause-of-death group.
#
# For ONS-only deaths, the denominator is all individuals in each
# broad cause-of-death group.
#
# For mismatched structured TPP death dates, the denominator is individuals
# with a structured TPP death date in each broad cause-of-death group.
#
# For mismatched TPP death records, the denominator is individuals with at
# least one TPP death record (structured death date or coded death) in each
# broad cause-of-death group.
#
# The two mismatch measures are retained separately at this stage to assess
# whether including coded TPP death records materially changes the results.

broad_cause_results <- analysis_cohort %>%
  group_by(broad_cause_group) %>%
  summarise(

    # All individuals in the broad cause-of-death group
    n_total = n(),

    # ONS-only death
    n_ons_only = sum(ons_only_death),

    # Individuals with a structured TPP date of death
    n_tpp_death_date = sum(has_tpp_death_date),

    # Individuals with at least one TPP death record
    # (structured death date or coded death)
    n_tpp_death_record = sum(has_tpp_death_record),

    # Structured TPP death date differs from ONS date of death
    n_mismatched_date = sum(mismatched_tpp_death_date),

    # At least one available TPP death date differs from ONS date of death
    n_mismatched_record = sum(mismatched_death_record),

    .groups = "drop"
  )

# -----------------------
# Apply disclosure control and calculate percentages
# Percentages are calculated from the disclosure-controlled counts;
# where either underlying count is redacted, the percentage is also redacted.
broad_cause_results <- broad_cause_results %>%
  mutate(
    # Apply SDC to counts
    n_total = apply_sdc(n_total),
    n_ons_only = apply_sdc(n_ons_only),
    n_tpp_death_date = apply_sdc(n_tpp_death_date),
    n_tpp_death_record = apply_sdc(n_tpp_death_record),
    n_mismatched_date = apply_sdc(n_mismatched_date),
    n_mismatched_record = apply_sdc(n_mismatched_record),
    pct_ons_only =
      round(
        100 * n_ons_only / n_total,
        1
      ),
    pct_mismatched_date =
      round(
        100 * n_mismatched_date / n_tpp_death_date,
        1
      ),
    pct_mismatched_record =
      round(
        100 * n_mismatched_record / n_tpp_death_record,
        1
      )
  )

# -----------------------
# Format broad cause-of-death results for output
# Replace redacted values with "[REDACTED]" and order columns for presentation

broad_cause_results <- broad_cause_results %>%
  mutate(
    across(
      c(
        n_total,
        n_ons_only,
        pct_ons_only,
        n_tpp_death_date,
        n_mismatched_date,
        pct_mismatched_date,
        n_tpp_death_record,
        n_mismatched_record,
        pct_mismatched_record
      ),
      ~ if_else(
        is.na(.x),
        "[REDACTED]",
        as.character(.x)
      )
    )
  ) %>%
  select(
    broad_cause_group,
    n_total,
    n_ons_only,
    pct_ons_only,
    n_tpp_death_date,
    n_mismatched_date,
    pct_mismatched_date,
    n_tpp_death_record,
    n_mismatched_record,
    pct_mismatched_record
  )


# -----------------------------------------------------------------------------
# Save broad cause-of-death results
# -----------------------------------------------------------------------------

write_csv(
  broad_cause_results,
  paste0(
    "output/",
    script_prefix,
    "_broad_cause_results.csv"
  )
)
